### ISSUE TITLE
Add screenshots of the plugin in the README

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/circlebars#8]

**Comment by TimoPurzner** [comment]
let me do it 👍

**Comment by itaditya** [comment]
Good work @thompsonemerson

**Comment by itaditya** [comment]
@ZeroSoulEater, if you like to contribute you can add new skins for the plugin or open new issues, I'm sure you'll find plenty

**Comment by itaditya** [comment]
And guys it would be awesome if you could star the repo
